import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faM,
  faW,
  faS,
  faT,
  faF,
  faCircle,
  faClock,
  faCalendar,
  faPlusCircle,
  faPersonRunning,
  faPersonSwimming,
  faFishFins,
  faTrash,
  faCircleExclamation,
  faFaceGrinTears,
  faCircleCheck,
  faFutbol,
  faSkiing,
  faDumbbell,
  faKeyboard,
  faCaretUp,
  faCaretDown,
  faCaretRight,
  faCaretLeft,
  faGear,
} from "@fortawesome/free-solid-svg-icons";

export function addIcons() {
  library.add(
    faM,
    faW,
    faS,
    faT,
    faF,
    faCircle,
    faClock,
    faCalendar,
    faPlusCircle,
    faPersonRunning,
    faPersonSwimming,
    faFishFins,
    faTrash,
    faCircleExclamation,
    faFaceGrinTears,
    faCircleCheck,
    faFutbol,
    faSkiing,
    faDumbbell,
    faKeyboard,
    faCaretUp,
    faCaretDown,
    faCaretRight,
    faCaretLeft,
    faGear
  );
}
